### PR TITLE
Resolved peterhanania#31

### PR DESCRIPTION
**Pull request by farkon00**
Made changes described in the issue.

### CODE REVIEW

**Comment by farkon00** [comment]
Updated version looks like this
Preview

**Review by peterhanania — CHANGES_REQUESTED** [review]
Thanks but please don't submit the PR with a change in package-lock 😄

**Comment by maxwellward** [comment]
> Updated version looks like this Preview

Both should probably use a consistent style of saying average. I personally prefer "average of" since it applies to all the numbers in the sentence, whereas ~ generally only applies to the number it's in front of.

**Comment by peterhanania** [comment]
This should all be re-done into a better design, so I will close this.

By better design I mean an icon etc.

**Pull request closed without merging**
