### PR TITLE
Fix typos and grammatical errors

### PR DESCRIPTION
**Pull request by maxwellward**
Changes:

- Changes "google analytics" to "Google Analytics", as it's the name of a brand.
- Removes extra padding around links in the privacy banner.
- Adjusting the wording of some statistics to flow better and be grammatically correct.

Looking for feedback on the following changes:

- Changing the "Read more" link on the privacy banner to its own button next to "Continue"
- Changed "is available for self hosting." text in privacy banner to "is available for analysis or self hosting."

I've also made a list of statistics that don't seem accurate or don't make sense and I will ask Discord about them and share the results.

### CODE REVIEW

**Comment by peterhanania** [comment]
I’ve just reviewed your code and everything seems good. Your code is well changed and your ideas are good. Thank you for your contribution. Regarding the analytics being inaccurate, I mean don’t expect them to be fully accurate because no one knows how they’re even collected. I will merge your contribution anyways. DM me to claim your contribution role on the discord server.

**Review by peterhanania — APPROVED** [review]
Thank you!

**Comment by maxwellward** [comment]
Thanks to for merging! Regarding the inaccuracies, I meant I'll ask Discord how they're collected so we can decide if they should be shown or not. Maybe they could be put into a "legacy" category if they're not being tracked anymore?

**Comment by peterhanania** [comment]
Let’s wait and see🙂

**Pull request merged**
