### PR TITLE
fixed issue #34 Currency issue is always on the left

### PR DESCRIPTION
**Pull request by michaela559**

### CODE REVIEW

**Comment by peterhanania** [comment]
Thanks, I'll look through it more when available. For next time though make sure you don't commit unused files! 
image

**Review by farkon00 — COMMENTED** [review]
How about formatting code to the already existing style.

```
export function getSymbol(amount, mostUsedCurrency) {
  let jsonData = require('../../components/json/other/currencies.json');
  let result;
  for (var i = 0; i < jsonData.length; i++){
    if (jsonData[i].currency === mostUsedCurrency) {
      if (jsonData[i].side === "left") {
        result = jsonData[i].symbol + amount;
      } else {
        result = amount + jsonData[i].symbol;
      }
      console.log(result);
      return result;
    }
  }
  return "";
}
```

**Comment by peterhanania** [comment]
I'll make sure to continue this when available

**Comment by peterhanania** [comment]
Fixed in last commit

**Pull request closed without merging**
